// DigitalShield Gemini Multimodal Analysis Service
// Dispatches analysis requests to the secure Cloudflare Worker backend.
// Keeps GEMINI_API_KEY strictly server-side as an encrypted Cloudflare Secret.

const DEPLOYED_WORKER_URL = 'https://digitalshield-api.digitalshield-api.workers.dev/api/analyze';
const DEPLOYED_TRAINING_URL = 'https://digitalshield-api.digitalshield-api.workers.dev/api/training/generate';

export function getAnalyzeEndpoint() {
  if (typeof window !== 'undefined' && window.location.hostname === 'localhost') {
    return '/api/analyze';
  }
  return DEPLOYED_WORKER_URL;
}

export function getTrainingEndpoint() {
  if (typeof window !== 'undefined' && window.location.hostname === 'localhost') {
    return '/api/training/generate';
  }
  return DEPLOYED_TRAINING_URL;
}

export async function callGeminiMultimodalAnalysis({ type, text = '', image = null }) {
  let imageBase64 = '';
  let mimeType = 'image/jpeg';

  if (image?.previewUrl) {
    const parts = image.previewUrl.split(';base64,');
    if (parts.length === 2) {
      mimeType = parts[0].replace('data:', '') || 'image/jpeg';
      imageBase64 = parts[1];
    } else {
      imageBase64 = image.previewUrl;
    }
  }

  const endpoint = getAnalyzeEndpoint();

  const payload = {
    type: type || 'General',
    text: (text || '').trim(),
    imageBase64,
    mimeType
  };

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(payload)
  });

  const data = await response.json().catch(() => null);

  if (!response.ok) {
    const errorMessage = data?.error || data?.details || `Backend API error (HTTP ${response.status}).`;
    throw new Error(errorMessage);
  }

  if (!data) {
    throw new Error('Received an empty response from the AI analysis service.');
  }

  return data;
}

export async function generateTrainingQuestions({ topic = 'general', count = 5 } = {}) {
  const endpoint = getTrainingEndpoint();

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ topic, count })
  });

  const data = await response.json().catch(() => null);

  if (!response.ok) {
    const errorMessage = data?.error || data?.details || `Question generation failed (HTTP ${response.status}).`;
    throw new Error(errorMessage);
  }

  if (!data || !Array.isArray(data.questions) || data.questions.length === 0) {
    throw new Error('No questions generated by AI service.');
  }

  return data.questions;
}
